### ISSUE TITLE
Modulo Desktop - Movimentação

### ISSUE THREAD

**Issue by Prof-Rayner** [Senac-SOR-ADS/Mapa-de-Sala#128]
@NickolasXL 

Ao fazer alguns testes na interface, quando ela é maximizada (ocupar tela inteira), se eu tentar arrastar a tela, ela funciona.
Porém não pode ser possível movimentar a tela, a não ser que a tela seja ajustada para ficar menor.

**Comment by NickolasXL** [comment]
Irei subir a função corrigida na pr.
    def mouseMoveEvent(self, event):
        if self.moving and not self.isMaximized():
            self.move(self.pos() + event.pos() - self.offset)
