### ISSUE TITLE
Query Banco de Dados

### ISSUE THREAD

**Issue by taviohenrique** [Senac-SOR-ADS/Mapa-de-Sala#13]
@Senac-SOR-ADS/back-end 

   Criamos algumas queries basicas para consultas como: Fazer uma reserva, Cadastrar pessoas, Retorna todas as pessoas que tem uma reserva com dia horario de inicio e fim, Mostrar todos os equipamentos já reservados.
   E também foi feito algumas verificações como:  Se a sala já está reservada nesse horario e se o docente já possui uma reserva no horario também.

Se alguém tiver alguma ideia para acrescentar comente aqui!

**Comment by Prof-Rayner** [comment]
Apresente quais foram as principais Query feitas, e se já esta dentro do projeto, aponto o caminho para avaliar a documentação.

Caso tenha dificuldades para ver quais precisão ser feitas; Analise os **prints** feitos dos relatórios que foram apresentados durante as reuniões de encontro com o Cliente.

Avalie os arquivos dentro do **Teams** da UC7

**Comment by taviohenrique** [comment]
Aqui estão algumas Querys preparadas e atualizadas para o novo banco de dados.
[QUERYS.docx](https://github.com/user-attachments/files/17014840/QUERYS.docx)
