### ISSUE TITLE
Importação do Banco em Um Unico Arquivo

### ISSUE THREAD

**Issue by NickolasXL** [Senac-SOR-ADS/Mapa-de-Sala#16]
Apresentar se é possível e viável centralizar a importação do banco de dados em um único arquivo na modelagem MVC?

**Comment by Prof-Rayner** [comment]
@NickolasXL valide a viabilidade de migrar o arquivo de conexão com o banco para a pasta de banco de dados.
Se fizer isso, será necessário alterar as importações dentro das classes de modelo.
Caso possível, a importação da classe usando o arquivo de inicialização da pasta do diretório.

**Comment by S4mK206** [comment]
Pelo que eu entendi, essa é uma forma de tratar os imports, deixa eles mais seguros, e organizados.

arquivo init:
![image](https://github.com/user-attachments/assets/04f051ae-d9d2-4cc5-99e7-1d53e3b63ce8)

arquivo aonde vai ser importado a conexão:
![image](https://github.com/user-attachments/assets/a6d29b2f-5d17-4c25-ba71-a111f5e11646)

Isso com apenas esse exemplo parece não fazer diferença, mas com vários arquivos fica bem melhor de realizar os imports.

Um exemplo da internet:
Sem tratamento com init
![image](https://github.com/user-attachments/assets/1dd4aef6-4f89-45de-b592-59e4fd058646)

Com init
![image](https://github.com/user-attachments/assets/db408398-12a3-4735-8349-dcdc64a1d062)

![image](https://github.com/user-attachments/assets/d34da7b0-c5aa-4a78-bcf4-2b177aa494d6)

**Comment by S4mK206** [comment]
Fiz as seguintes alterações nos arquivos do diretório da model. como no exemplo abaixo, troquei todas as importações, tirando a dependência do arquivo, e adicionando ao init.
Acho a implementação viável, são detalhes simples que vão fazer diferença mais pra frente quando o projeto estiver mais encorpado.
 
![image](https://github.com/user-attachments/assets/f2c215e2-f133-4080-b04a-96a63a085f6f)

![image](https://github.com/user-attachments/assets/a66f1016-2a80-4225-9674-3373598284aa)

Está feito, agora preciso de uma decisão para implementar, ou não.

**Comment by Prof-Rayner** [comment]
@NickolasXL 
Apresenta alguma atualização sobre como realizar o processo?

**Comment by NickolasXL** [comment]
Não vai ser viável a implementação, pois não consegui achar informações e exemplos com base na pesquisa que foi feita.
