### ISSUE TITLE
Interface Login Transparente

### ISSUE THREAD

**Issue by leleeox** [Senac-SOR-ADS/Mapa-de-Sala#21]
Revisei a interface do Vitor e aprimorei colocando botão de sair do aplicativo e informação de erro de dados não inseridos.
![InterfaceLogin](https://github.com/user-attachments/assets/00be1bd8-297b-404d-8ccb-7fcc6469415f)
![Captura de tela 2024-09-11 120346](https://github.com/user-attachments/assets/3b3e89b8-4798-4571-ac80-76a7a47cbc27)

**Comment by Prof-Rayner** [comment]
@leleeox 
Abre a **Pull Request**, e detalhe tudo que foi feito para essa interface.
