### ISSUE TITLE
Dificuldade em acessar o .env

### ISSUE THREAD

**Issue by S4mK206** [Senac-SOR-ADS/Mapa-de-Sala#22]
Verifiquei que o arquivo .env foi ignorado pelo gitignore, e gostaria que ele ficasse dentro do diretório da model, ou em um diretório a parte, que eu tenha acesso.
Estou com dificuldade ao conectar com o banco e acredito que tendo acesso a esse arquivo, seria mais fácil de trabalhar. 

![image](https://github.com/user-attachments/assets/57a175cb-aae1-436b-8bdc-794b050301ff)

**Comment by Prof-Rayner** [comment]
Gostei da pergunta, @S4mK206 

Geralmente, o arquivo **.env**, ele guarda as informações sensíveis do projeto como **Secret Key**.
Esse arquivo realmente não é carregado para o github, pois ele pode expor informações sensíveis, sendo assim, todos os colaboradores do projeto devem conter esse arquivo em seu **repositório local**, mas como ele não esta no github, podemos subir um arquivo **Template** como **.env-exemplo**.

### .env-exemplo

```python
HOST ="localhost"
LOGIN = "usuario"
PASSWORD = "senha123"
DATABASE = "banco_teste"
```

Assim garante que todos precisam criar e preencher com as informações locais para poder realizar o teste.
Mantendo a integridade do projeto sem expor informações sensíveis.

**Comment by Prof-Rayner** [comment]
@Senac-SOR-ADS/dba @Senac-SOR-ADS/back-end @Senac-SOR-ADS/front-end 
Bom dia a todos, 

Conforme conversado na Daily de Quarta (18/09/2024), centralizamos todo o nosso banco de dados no equipamento do @taviohenrique, sendo assim, todos validem a mensagem que o @S4mK206 mandou no **Teams** para realizar as configurações da variável de ambiente de conexão com o banco de dados.

Assim que atualizarem o repositório, necessário criar o arquivo **.env** na pasta de **modelo**.


## .env

```python
HOST ="localhost"
LOGIN = "usuario"
PASSWORD = "senha123"
DATABASE = "banco_teste"
```
Substitua os valores de conexão com o que foi passado no **Teams**, posteriormente cada um terá o seu próprio usuário para realizar as manipulações no banco.
