### ISSUE TITLE
Modelo Conceitual

### ISSUE THREAD

**Issue by Prof-Rayner** [Senac-SOR-ADS/Mapa-de-Sala#3]
Elaborar a modelagem conceitual do banco de dados, e identificação das entidades e seus atributos.
Definição da cardinalidade entre as entidades.

**Comment by taviohenrique** [comment]
![conceitual v4](https://github.com/user-attachments/assets/914eb590-8748-4776-8c26-09106a04c656)

Começamos a identificar as entidades e seus atributos.
Após identificarmos, começamos com as cardinalidades e definimos as entidades fracas e fortes!

**Comment by Prof-Rayner** [comment]
Referente ao modelo, tem mais alguma necessidade de alteração ou já esta finalizado?
Caso esteja finalizado, pode encerrar a issue para dar andamento nos pontos de entregas

**Comment by taviohenrique** [comment]
Já está finalizado certinho

**Comment by gabrieladprestes** [comment]
Abrindo a issue para podermos remodelar o modelo, agora que nos demos conta de que precisamos de mais campos para a relação de quantidade de reserva de equipamentos

**Comment by gabrieladprestes** [comment]
Com o decorrer do projeto, precisaremos atualizar os modelos do banco de dados
