### ISSUE TITLE
Modelo Lógico

### ISSUE THREAD

**Issue by Prof-Rayner** [Senac-SOR-ADS/Mapa-de-Sala#4]
Apresentar o conceito de modelo lógico do banco de dados
Quais suas relações entre as tabelas
Definição do tipos de seus atributos
Chaves primárias e estrangeiras

**Comment by Prof-Rayner** [comment]
Como o modelo conceitual já esta pronto e esta etapa tecnicamente esta pronto, acrescente na documentação o modelo.
Se possível já prepare as Query para uso no projeto.

Caso haja alterações no projeto do modelo conceitual, reabra a ISSUE para explicar as alterações e o porque.

**Comment by taviohenrique** [comment]
Estamos reabrindo a issues pois apareceu mudanças que deverá ser feitas no equipamento

**Comment by gabrieladprestes** [comment]
Depois de revisar o modelo, criamos uma nova entidade para conter todos os equipamentos que estão sendo utilizados em reservas, junto com a quantidade reservada

![logico v5](https://github.com/user-attachments/assets/bcbab6a3-5b28-4804-a8d9-4fc1c5cc1d2e)
