### ISSUE TITLE
Modelagem da Interface

### ISSUE THREAD

**Issue by Tortugazil** [Senac-SOR-ADS/Mapa-de-Sala#6]
Estou fazendo modelagem para interface - Home, porém, gostaria de possíveis ideias sobre o que será utilizável e inutilizável, estou usando 2 modelos para fazer a Home e irei mesclar ambas para que fique adapto com o nosso projeto.

As fotos abaixo são os dois modelos que estou usando:

A primeira foto é o protótipo da Home e a Segunda foto é o modelo inicial ao qual irei mesclar com a principal futuramente

![Protótipo da Home](https://github.com/user-attachments/assets/f4eaf860-5574-48ba-95e2-e56e8036537c)
![Modelo 2 da Home](https://github.com/user-attachments/assets/69f1f79d-1cd6-4c3b-ae96-431d890dc48d)
![Modelo 2 - Home](https://github.com/user-attachments/assets/4e939cd7-6068-4242-a507-cef092213a51)

**Comment by Prof-Rayner** [comment]
Bom dia  @Tortugazil,

Gostei da ideia de utilizar um projeto como template para agilizar o projeto, porém precisa ser modificado o a interface para fazer sentido no uso do cliente.

Tente avaliar, como voces ( @Senac-SOR-ADS/front-end  ) irão implementar as telas de interações, pois como apresentado nas imagens de referencia, as telas serão integradas no frame principal (QMainWindow).

Relatórios podem ser em telas a parte, pois o cliente pode gerar mais de 1 relatório, para fim de comparação entre eles.


Coisas para alterar: Paleta de cores, pois precisa estar com a cara do cliente.
